# Generated by Django 5.2.8 on 2025-11-30 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Your Name', max_length=100)),
                ('tagline', models.CharField(blank=True, default='Digital Creator & Problem Solver', max_length=255)),
                ('bio', models.TextField(blank=True, default='Write your bio here. Include experience and mission.')),
                ('skills', models.TextField(blank=True, default='Python\nDjango\nJavaScript\nUI/UX')),
                ('github', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
            },
        ),
    ]
