# Generated by Django 5.2.8 on 2025-12-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pot', '0002_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='budget',
            field=models.CharField(blank=True, choices=[('', 'Not sure / Discuss'), ('1k-5k', '$1k–$5k'), ('5k-20k', '$5k–$20k'), ('20k+', '$20k+')], default='', max_length=20),
        ),
    ]
